use lazy_static::lazy_static;
use crate::extract_tests::TestFile;
lazy_static! {
    pub static ref TEST_FILES: Vec<TestFile<'static>> = vec![
        TestFile::new(
            "argument_and_locals",
            39,
            60,
        ),
        TestFile::new(
            "argument_form_expr",
            39,
            42,
        ),
        TestFile::new(
            "argument_used_twice_form_expr",
            39,
            42,
        ),
        TestFile::new(
            "break_from_nested_and_outer_loops",
            52,
            186,
        ),
        TestFile::new(
            "break_from_nested_loop",
            52,
            133,
        ),
        TestFile::new(
            "break_loop",
            52,
            102,
        ),
        TestFile::new(
            "break_loop_nested",
            56,
            123,
        ),
        TestFile::new(
            "break_loop_nested_labeled",
            58,
            69,
        ),
        TestFile::new(
            "break_loop_with_if",
            56,
            103,
        ),
        TestFile::new(
            "break_stmt",
            46,
            57,
        ),
        TestFile::new(
            "break_with_value",
            59,
            148,
        ),
        TestFile::new(
            "break_with_value_and_label",
            65,
            159,
        ),
        TestFile::new(
            "break_with_value_and_return",
            49,
            148,
        ),
        TestFile::new(
            "closure_arguments",
            57,
            88,
        ),
        TestFile::new(
            "comments_in_block_expr",
            22,
            133,
        ),
        TestFile::new(
            "continue_loop_nested_labeled",
            58,
            72,
        ),
        TestFile::new(
            "copy_custom_used_after",
            87,
            99,
        ),
        TestFile::new(
            "copy_used_after",
            32,
            42,
        ),
        TestFile::new(
            "does_not_add_extra_whitespace",
            27,
            39,
        ),
        TestFile::new(
            "does_not_import_control_flow",
            17,
            44,
        ),
        TestFile::new(
            "dont_emit_type_with_hidden_lifetime_parameter",
            73,
            80,
        ),
        TestFile::new(
            "empty_generic_param_list",
            52,
            59,
        ),
        TestFile::new(
            "extract_cast",
            25,
            36,
        ),
        TestFile::new(
            "extract_does_not_tear_body_apart",
            16,
            25,
        ),
        TestFile::new(
            "extract_does_not_tear_comments_apart",
            18,
            52,
        ),
        TestFile::new(
            "extract_does_not_wrap_res_in_res",
            35,
            74,
        ),
        TestFile::new(
            "extract_from_nested",
            76,
            81,
        ),
        TestFile::new(
            "extract_function_copies_comment_at_end",
            33,
            65,
        ),
        TestFile::new(
            "extract_function_copies_comment_at_start",
            33,
            65,
        ),
        TestFile::new(
            "extract_function_copies_comment_in_between",
            27,
            81,
        ),
        TestFile::new(
            "extract_function_copies_comment_indented",
            33,
            95,
        ),
        TestFile::new(
            "extract_function_does_preserve_whitespace",
            33,
            61,
        ),
        TestFile::new(
            "extract_function_from_trait_with_existing_non_empty_impl_block",
            186,
            191,
        ),
        TestFile::new(
            "extract_function_long_form_comment",
            33,
            64,
        ),
        TestFile::new(
            "extract_method_from_trait_impl",
            129,
            139,
        ),
        TestFile::new(
            "extract_method_from_trait_with_existing_non_empty_impl_block",
            166,
            176,
        ),
        TestFile::new(
            "extract_method_from_trait_with_multiple_existing_impl_blocks",
            301,
            311,
        ),
        TestFile::new(
            "extract_method_from_trait_with_multiple_existing_trait_impl_blocks",
            441,
            451,
        ),
        TestFile::new(
            "extract_mut_ref_param_has_no_mut_binding_in_loop",
            140,
            148,
        ),
        TestFile::new(
            "extract_partial_block",
            62,
            86,
        ),
        TestFile::new(
            "extract_partial_block_single_line",
            44,
            50,
        ),
        TestFile::new(
            "extract_return_stmt",
            23,
            35,
        ),
        TestFile::new(
            "extract_with_await",
            17,
            39,
        ),
        TestFile::new(
            "extract_with_await_and_result_not_producing_match_expr",
            40,
            69,
        ),
        TestFile::new(
            "extract_with_await_and_result_producing_match_expr",
            55,
            170,
        ),
        TestFile::new(
            "extract_with_await_in_args",
            17,
            59,
        ),
        TestFile::new(
            "extract_with_macro_arg",
            23,
            31,
        ),
        TestFile::new(
            "filter_unused_generics",
            59,
            66,
        ),
        TestFile::new(
            "filter_unused_where_clause",
            70,
            77,
        ),
        TestFile::new(
            "filters_unused_nested_generics",
            181,
            200,
        ),
        TestFile::new(
            "filters_unused_nested_where_clauses",
            211,
            230,
        ),
        TestFile::new(
            "function_expr",
            16,
            26,
        ),
        TestFile::new(
            "indented_stmts",
            55,
            89,
        ),
        TestFile::new(
            "indented_stmts_inside_mod",
            82,
            120,
        ),
        TestFile::new(
            "it_should_not_generate_duplicate_function_names",
            21,
            31,
        ),
        TestFile::new(
            "method_to_freestanding",
            59,
            62,
        ),
        TestFile::new(
            "method_with_mut",
            67,
            79,
        ),
        TestFile::new(
            "method_with_reference",
            70,
            83,
        ),
        TestFile::new(
            "multi_variables_defined_inside_and_used_after_mutably_no_ret",
            32,
            111,
        ),
        TestFile::new(
            "mut_field_from_outer_scope",
            66,
            75,
        ),
        TestFile::new(
            "mut_method_call",
            133,
            141,
        ),
        TestFile::new(
            "mut_nested_field_from_outer_scope",
            165,
            205,
        ),
        TestFile::new(
            "mut_param_because_of_mut_ref",
            36,
            65,
        ),
        TestFile::new(
            "mut_param_many_usages_expr",
            236,
            420,
        ),
        TestFile::new(
            "mut_param_many_usages_stmt",
            236,
            370,
        ),
        TestFile::new(
            "mut_var_from_outer_scope",
            36,
            43,
        ),
        TestFile::new(
            "nested_generics",
            155,
            174,
        ),
        TestFile::new(
            "nested_where_clauses",
            179,
            198,
        ),
        TestFile::new(
            "no_args_for",
            16,
            36,
        ),
        TestFile::new(
            "no_args_from_binary_expr",
            20,
            25,
        ),
        TestFile::new(
            "no_args_from_binary_expr_in_module",
            39,
            44,
        ),
        TestFile::new(
            "no_args_from_binary_expr_indented",
            16,
            25,
        ),
        TestFile::new(
            "no_args_from_loop_unit",
            16,
            49,
        ),
        TestFile::new(
            "no_args_from_loop_with_return",
            24,
            75,
        ),
        TestFile::new(
            "no_args_from_match",
            29,
            94,
        ),
        TestFile::new(
            "no_args_from_stmt_unit",
            32,
            62,
        ),
        TestFile::new(
            "no_args_from_stmt_with_last_expr",
            39,
            60,
        ),
        TestFile::new(
            "no_args_if",
            16,
            27,
        ),
        TestFile::new(
            "no_args_if_else",
            23,
            47,
        ),
        TestFile::new(
            "no_args_if_let_else",
            23,
            59,
        ),
        TestFile::new(
            "no_args_match",
            23,
            83,
        ),
        TestFile::new(
            "no_args_while",
            16,
            30,
        ),
        TestFile::new(
            "non_tail_expr_of_tail_expr_loop",
            34,
            77,
        ),
        TestFile::new(
            "non_tail_expr_of_tail_if_block",
            55,
            132,
        ),
        TestFile::new(
            "non_tail_expr_with_comment_of_tail_expr_loop",
            34,
            99,
        ),
        TestFile::new(
            "nontrivial_patterns_define_variables",
            38,
            66,
        ),
        TestFile::new(
            "param_from_closure",
            39,
            44,
        ),
        TestFile::new(
            "param_usage_in_macro",
            23,
            41,
        ),
        TestFile::new(
            "param_usage_in_macro_with_nested_tt",
            23,
            51,
        ),
        TestFile::new(
            "param_usage_in_macro_with_nested_tt_2",
            23,
            56,
        ),
        TestFile::new(
            "part_of_expr_stmt",
            16,
            17,
        ),
        TestFile::new(
            "preserve_generics",
            31,
            38,
        ),
        TestFile::new(
            "preserve_generics_from_body",
            34,
            46,
        ),
        TestFile::new(
            "preserve_where_clause",
            39,
            46,
        ),
        TestFile::new(
            "reference_mutable_param_with_further_usages",
            76,
            90,
        ),
        TestFile::new(
            "reference_mutable_param_without_further_usages",
            76,
            90,
        ),
        TestFile::new(
            "return_from_nested_fn",
            52,
            139,
        ),
        TestFile::new(
            "return_from_nested_loop",
            42,
            134,
        ),
        TestFile::new(
            "return_to_parent",
            39,
            84,
        ),
        TestFile::new(
            "should_increment_suffix_until_it_finds_space",
            60,
            70,
        ),
        TestFile::new(
            "struct_with_two_fields_pattern_define_variables",
            52,
            101,
        ),
        TestFile::new(
            "tail_expr_no_extra_control_flow",
            39,
            92,
        ),
        TestFile::new(
            "tail_expr_of_tail_block_nested",
            47,
            196,
        ),
        TestFile::new(
            "try_and_return_ok",
            51,
            134,
        ),
        TestFile::new(
            "try_option",
            85,
            120,
        ),
        TestFile::new(
            "try_option_unit",
            46,
            81,
        ),
        TestFile::new(
            "try_option_with_return",
            46,
            128,
        ),
        TestFile::new(
            "try_result",
            51,
            86,
        ),
        TestFile::new(
            "try_result_with_return",
            51,
            135,
        ),
        TestFile::new(
            "two_arguments_form_expr",
            55,
            60,
        ),
        TestFile::new(
            "two_variables_defined_inside_and_used_after_no_ret",
            32,
            66,
        ),
        TestFile::new(
            "unresolveable_types_default_to_placeholder",
            51,
            54,
        ),
        TestFile::new(
            "variable_defined_inside_and_used_after_mutably_no_ret",
            32,
            50,
        ),
        TestFile::new(
            "variable_defined_inside_and_used_after_no_ret",
            32,
            46,
        ),
    ];
}
